package org.omg.PortableServer;


/**
* org/omg/PortableServer/ThreadPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u191/11896/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Saturday, October 6, 2018 9:30:42 AM PDT
*/


/**
	 * The ThreadPolicy specifies the threading model 
	 * used with the created POA. The default is 
	 * ORB_CTRL_MODEL.
	 */
public interface ThreadPolicy extends ThreadPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface ThreadPolicy
